SNUTT-125 강의평 기능을 위한 model 및 repository 개발
wafflestudio/snutt-ev pull request #1
Opened 2021-07-05 19:21 UTC by davin111

### 서버 자체를 새로 만드는 것이므로, 하나의 PR 안에 지나치게 많은 내용이 들어가지 않도록, 여러 PR로 끊어서 갈 예정
### 한 덩어리가 크지 않도록 가급적 할 것이므로, 빠른 리뷰 부탁드립니다 

# Major Changes
## 1. 강의평 기능을 위한 model 및 repository 개발
- 
<img width="824" alt="스크린샷 2021-07-06 04 17 24" src="https://user-images.githubusercontent.com/35535636/124511436-13a01280-de11-11eb-8c1b-0c2f86a2a216.png">

- 기존 설계에 따라, Lecture table(필요성이 아직 불명확하여)을 제외한 entity 및 repository 정의

## 2. POST /api/v1/evaluation/ 개발
- controller-service-repository로 이어지는 기본적인 flow의 예시를 들기 위해, 강의평을 생성하는 API 하나 기본적 개발
- Request, Dto 등의 data class에서 받고 넘겨주는 것에는 고민이 되어 있지 않음. 그냥 예시일 뿐임.

## 3. 간단한 API 동작 확인을 위한 DataLoader 정의
- SemesterLecture에 예시 강의 하나를 insert하도록 함.

## 4. Java Version 16 -> 11로 하향
- 아직 IntelliJ에서 Java 16을 사용하는 데에 약간의 불편함이 있음을 확인하고, 별다른 이점이 없다고 판단하여 Java 11로 하향

2021-07-06 10:54 UTC, Hank-Choi requested changes
코멘트 확인 부탁드립니다

2021-07-06 10:54 UTC, Hank-Choi commented on src/main/kotlin/com/wafflestudio/SnuttUserFilter.kt
> +            httpResponse.sendError(HttpServletResponse.SC_UNAUTHORIZED)
이거 문제 있어용 mongoDB ID는 12byte hexadecimal값이라 24자리 string입니다.

2021-07-06 10:54 UTC, Hank-Choi commented on src/main/kotlin/com/wafflestudio/snuttev/config/DataSourceConfig.kt
> +}
이거 없이도 spring에서 자동으로 설정하고 동작하지 않나요?

2021-07-06 10:55 UTC, davin111 commented on src/main/kotlin/com/wafflestudio/SnuttUserFilter.kt
> +            httpResponse.sendError(HttpServletResponse.SC_UNAUTHORIZED)
아 ㅋㅋㅋㅋㅋㅋㅋ snutt user id 말이죠? 너무 자연스레 long인줄... 죄송합니다... 확인도 안 하고 🙏

2021-07-06 10:56 UTC, Hank-Choi reviewed
위 리뷰와 연관된 코멘트입니다

2021-07-06 10:56 UTC, Hank-Choi commented on src/main/kotlin/com/wafflestudio/snuttev/controller/EvaluationController.kt
> +        @RequestAttribute(value = "UserId") userId: Long,
마찬가지로 여기

2021-07-06 10:56 UTC, Hank-Choi commented on src/main/kotlin/com/wafflestudio/snuttev/dao/model/EvaluationComment.kt
> +    val userId: Long,
여기

2021-07-06 10:56 UTC, Hank-Choi commented on src/main/kotlin/com/wafflestudio/snuttev/dao/model/LectureEvaluation.kt
> +    val userId: Long,
여기

2021-07-06 10:56 UTC, Hank-Choi commented on src/main/kotlin/com/wafflestudio/snuttev/service/EvaluationService.kt
> +    val userId: Long,
요기요기

2021-07-25 07:54 UTC, davin111 commented on src/main/kotlin/com/wafflestudio/SnuttUserFilter.kt
> +            httpResponse.sendError(HttpServletResponse.SC_UNAUTHORIZED)
반영했습니다.

2021-07-25 07:54 UTC, davin111 commented on src/main/kotlin/com/wafflestudio/snuttev/config/DataSourceConfig.kt
> +}
반영했습니다.

2021-07-25 07:55 UTC, davin111 commented
@Hank-Choi userId를 String으로 바꾸고, DataSourceConfig 지우고, Lecture model을 신설하여 SemesterLecture model와 역할 구분했습니다.

2021-07-25 07:58 UTC, Hank-Choi approved these changes
LGTM 🚀

2021-07-25 07:58 UTC, merged